name: Run Tests

# Triggers the workflow on push or pull request to the 'main' branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    # Define the environment to run the tests
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository (pulls the code from the repo)
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify the version of Python you want

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install the dependencies from your requirements file

      # Step 4: Run the tests
      - name: Run tests with pytest
        run: |
          pytest  # This assumes you use pytest as your test runner
